# Mobb/Checkamrx Fixer on pull requests
# This workflow defines the needed steps to run Checkmarx on every pull request and pass the results to Mobb Fixer.
#
# Secrets in use (add your missing ones):
# CX_TENANT - your Checkmarx tenant name (found in your Checkmarx settings)
# CX_API_TOKEN - your Checkmarx credentials (find how to get it here: https://checkmarx.com/resource/documents/en/34965-68775-generating-a-refresh-token--api-key-.html)
# CX_BASE_URI - your Checkmarx app url, e.g. "https://ast.checkmarx.net/"
# CX_BASE_AUTH_URI - your Checkmarx auth url, e.g. "https://iam.checkmarx.net/"
# MOBB_API_TOKEN - your mobb user credentials (autumatially set if you used the Mobb app to configure the integration)
# GITHUB_TOKEN - automatically set by GitHub

name: "Mobb/Checkmarx"

on:
  issue_comment:
    types: [created]


jobs:
  scan-and-fix:
    name: Issue Comment
    if: ${{ github.event.issue.pull_request }} # This makes sure that the comment originates from a PR and not an issue comment
    runs-on: 'ubuntu-latest'
    timeout-minutes: 360
    permissions:
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test
        run: |
          echo A comment on PR $NUMBER
          echo ${{ github.event.issue.payload.comment }}
          env
        env:
          NUMBER: ${{ github.event.issue.number }}

  
      # - name: Run Mobb on the findings and get fixes
      #   if: always()
      #   uses: mobb-dev/action/review@v1.1
      #   with:
      #     report-file: cx_result.json
      #     api-key: ${{ secrets.MOBB_API_TOKEN }}
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     scanner: checkmarx
